const {chromium} = require(process.env.PLAYWRIGHT_MODULE || 'playwright');
const fs = require('node:fs');
fs.mkdirSync('output/qa', {recursive:true});
(async()=>{
  const browser=await chromium.launch({executablePath:process.env.CHROME_PATH,headless:true});
  const page=await browser.newPage({viewport:{width:1366,height:768}});
  const errors=[];page.on('pageerror',error=>errors.push(error.message));
  await page.goto(process.env.BD2_URL || 'http://127.0.0.1:8000');
  await page.getByText('Motor conectado',{exact:true}).waitFor();
  await page.getByRole('button',{name:'Ejecutar consulta'}).click();
  await page.waitForFunction(()=>document.getElementById('status').textContent.includes('11 filas encontradas'));
  if(await page.locator('#results tbody tr').count()!==11)throw Error('Resultados incorrectos');
  await page.locator('summary').first().click();
  await page.screenshot({path:'output/qa/frontend-1366.png',fullPage:true});
  await page.setViewportSize({width:1920,height:1080});
  await page.screenshot({path:'output/qa/frontend-1920.png',fullPage:true});
  await page.locator('#sql').fill('SELECT * FROM products;');
  await page.locator('#run').click();
  await page.waitForFunction(()=>document.getElementById('status').textContent.includes('Consulta completada') && !document.getElementById('run').disabled);
  await page.locator('#next').click();
  await page.waitForFunction(()=>document.getElementById('page-number').textContent==='2');
  if((await page.locator('#results tbody tr').first().innerText()).split('\t')[1]!=='101')throw Error('Paginación incorrecta');
  await page.locator('#sql').fill('SELECT * FROM tabla_inexistente;');
  const paginationRequest=page.waitForRequest(request=>request.url().endsWith('/api/query'));
  await page.locator('#page-size').selectOption('25');
  const request=await paginationRequest;
  if(request.postDataJSON().sql!=='SELECT * FROM products;')throw Error('La paginación ejecutó texto editado');
  await page.waitForFunction(()=>document.querySelectorAll('#results tbody tr').length===25 && !document.getElementById('run').disabled);
  await page.locator('#run').click();
  await page.locator('#status.error').waitFor();
  if(await page.locator('#disk-reads').innerText()!=='—')throw Error('Métrica obsoleta tras error');
  await page.setViewportSize({width:760,height:900});
  await page.screenshot({path:'output/qa/frontend-760.png',fullPage:true});
  const overflow=await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth);
  if(overflow)throw Error('Desbordamiento horizontal del documento');
  if(errors.length)throw Error(errors.join('\n'));
  fs.writeFileSync('output/qa/frontend-checks.json',JSON.stringify({viewports:[1366,1920,760],real_rows:11,pagination:true,pagination_uses_executed_sql:true,error_state:true,console_errors:errors},null,2));
  console.log('Frontend OK: datos reales, paginación, errores, tres tamaños y sin errores JS');
  await browser.close();
})().catch(error=>{console.error(error);process.exit(1)});

